- hosts: localhost
  become: true
  tasks:
    - name: Installer Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Créer une page HTML simple
      copy:
        content: "<html><h1>Bonjour depuis Ansible!</h1></html>"
        dest: /var/www/html/index.html

    - name: Démarrer le service Apache
      service:
        name: apache2
        state: started
        enabled: yes
